#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es Temperature Temperatura
::msgcat::mcset es Thermal Termal
::msgcat::mcset es {Composition Material} {Material De la Composición}
::msgcat::mcset es 1-X 1-X
::msgcat::mcset es 2-Y 2-Y
::msgcat::mcset es 3-Z 3-Z
::msgcat::mcset es 4-RX 4-rx
::msgcat::mcset es 5-RY 5-ry
::msgcat::mcset es 6-RZ 6-rz
::msgcat::mcset es ACCELERATION ACELERACIÓN
::msgcat::mcset es Absorptivity: Absorbencia:
::msgcat::mcset es {Advanced Conditions} {Condiciones Avanzadas}
::msgcat::mcset es {All bars and beams must have Local Axes defined.} {Todas las barras y vigas deben tener hachas locales definidas.}
::msgcat::mcset es {Alternative Format:} {Formato Alternativo:}
::msgcat::mcset es Amplitude(A): Amplitude(A):
::msgcat::mcset es {Area factor:} {Factor del área:}
::msgcat::mcset es Auto Automóvil
::msgcat::mcset es {Auto alt} {Automóvil alt}
::msgcat::mcset es BASIC BASIC
::msgcat::mcset es CONM1 CONM1
::msgcat::mcset es CONM2 CONM2
::msgcat::mcset es {Concentrated Mass Element} {Elemento Total Concentrado}
::msgcat::mcset es Connections Conexiones
::msgcat::mcset es Constraints Apremios
::msgcat::mcset es Contact Contacto
::msgcat::mcset es {Convection Boundary} {Límite De la Convección}
::msgcat::mcset es {Convection coef.:} {Convección coef.:}
::msgcat::mcset es {Coord System:} {Sistema De Coord:}
::msgcat::mcset es DISPLACEMENT DISLOCACIÓN
::msgcat::mcset es Data Datos
::msgcat::mcset es {Defines a boundary condition surface element} {Define un elemento de la superficie de la condición de límite}
::msgcat::mcset es {Defines a convetion boundary for heat transfer analysis} {Define un límite del convetion para el análisis del traspaso térmico}
::msgcat::mcset es {Defines a heat flux over boundary heat lines} {Define un flujo del calor sobre líneas del calor del límite}
::msgcat::mcset es {Defines a heat flux over boundary heat points} {Define un flujo del calor sobre puntos del calor del límite}
::msgcat::mcset es {Defines a radiation boundary for heat transfer analysis} {Define un límite de la radiación para el análisis del traspaso térmico}
::msgcat::mcset es {Defines a rate of volumetric heat addition in a conduction element} {Define un índice de la adición volumétrica del calor en un elemento de la conducción}
::msgcat::mcset es {Defines initial temperature for all nodes of the geometric entity} {Define la temperatura inicial para todos los nodos de la entidad geométrica}
::msgcat::mcset es {Degree of freedom:} {Grado de libertad:}
::msgcat::mcset es Description Descripción
::msgcat::mcset es {Disconnect X Displacement} {Desconecte La Dislocación De X}
::msgcat::mcset es {Disconnect X Rotation} {Desconecte La Rotación De X}
::msgcat::mcset es {Disconnect Y Displacement} {Desconecte La Dislocación De Y}
::msgcat::mcset es {Disconnect Y Rotation} {Desconecte La Rotación De Y}
::msgcat::mcset es {Disconnect Z Displacement} {Desconecte La Dislocación De Z}
::msgcat::mcset es {Disconnect Z Rotation} {Desconecte La Rotación De Z}
::msgcat::mcset es {Dynamics Loads} {Cargas De la Dinámica}
::msgcat::mcset es ELEMENT ELEMENTO
::msgcat::mcset es ESE ESE
::msgcat::mcset es Emissivity: Emisividad:
::msgcat::mcset es {Exponential coefficient(C):} {Coefficient(C) exponencial:}
::msgcat::mcset es FORCE FUERZA
::msgcat::mcset es {Fixed Temperature} {Temperatura Fija}
::msgcat::mcset es {Flux Magnitude:} {Magnitud Del Flujo:}
::msgcat::mcset es Format: Formato:
::msgcat::mcset es {Freq Dynamic Type1} {Freq Type1 Dinámico}
::msgcat::mcset es {Freq Dynamic Type2} {Freq Type2 Dinámico}
::msgcat::mcset es {Frequency in cycles per unit time(f):} {Frecuencia en ciclos por time(f) de la unidad:}
::msgcat::mcset es GLOBAL GLOBAL
::msgcat::mcset es {Growth coefficient(B):} {Coefficient(B) del crecimiento:}
::msgcat::mcset es {Heat Boundaries} {Límites Del Calor}
::msgcat::mcset es {Heat Boundary} {Límite Del Calor}
::msgcat::mcset es {Heat Flux} {Flujo Del Calor}
::msgcat::mcset es I1 I1
::msgcat::mcset es I2 I2
::msgcat::mcset es I3 I3
::msgcat::mcset es Id Identificar
::msgcat::mcset es {Inferior Time Limit(T1):} {Tiempo Inferior Limit(T1):}
::msgcat::mcset es {Initial Conditions} {Condiciones Iniciales}
::msgcat::mcset es {Initial Temperature} {Temperatura Inicial}
::msgcat::mcset es {Initial Temperature:} {Temperatura Inicial:}
::msgcat::mcset es {Initial displacement:} {Dislocación inicial:}
::msgcat::mcset es {Initial velocity:} {Velocidad inicial:}
::msgcat::mcset es {Kind of Output:} {Clase de salida:}
::msgcat::mcset es LOAD CARGA
::msgcat::mcset es Line-Constraints Li'nea-Constreñimientos
::msgcat::mcset es Line-Enforced-Displacement {Li'nea-Hacer cumplir-Dislocación}
::msgcat::mcset es Line-Local-Axes Li'nea-Local-Hachas
::msgcat::mcset es Line-Pressure-Load Li'nea-Presión-Carga
::msgcat::mcset es Line-Projected-Pressure-Load Li'nea-Proyectar-Presión-Carga
::msgcat::mcset es Line-Triangular-Pressure-Load Li'nea-Triangular-Presión-Carga
::msgcat::mcset es {Load Type} {Tipo De la Carga}
::msgcat::mcset es {Local Axes} {Hachas Locales}
::msgcat::mcset es Mass Masa
::msgcat::mcset es {Mass Value:} {Valor Total:}
::msgcat::mcset es {Mass moments of inertia:} {Momentos totales de la inercia:}
::msgcat::mcset es Master Amo
::msgcat::mcset es {Master slave:} {Esclavo principal:}
::msgcat::mcset es {Material Axes} {Hachas Materiales}
::msgcat::mcset es Moment Momento
::msgcat::mcset es {Mx-Enforced Displacement:} {Dislocación MX-Hecha cumplir:}
::msgcat::mcset es Mx-Force MX-Fuerza
::msgcat::mcset es {My-Enforced Displacement:} {Dislocación Mi-Hecha cumplir:}
::msgcat::mcset es My-Force Mi-Fuerza
::msgcat::mcset es {Mz-Enforced Displacement:} {Dislocación Mz-Hecha cumplir:}
::msgcat::mcset es Mz-Force Mz-Fuerza
::msgcat::mcset es NORMAL NORMAL
::msgcat::mcset es {Normal Inward:} {Normal Interno:}
::msgcat::mcset es Normal-Surface-Load Normal-Superficie-Carga
::msgcat::mcset es {Offset distances:} {Distancias compensadas:}
::msgcat::mcset es Orientation Orientación
::msgcat::mcset es {Output Set Lines} {Líneas Determinadas De la Salida}
::msgcat::mcset es {Output Set Nodes} {Nodos Determinados De la Salida}
::msgcat::mcset es {Output Set Surfaces} {Superficies Determinadas De la Salida}
::msgcat::mcset es PROJECTED PROYECTADO
::msgcat::mcset es {Phase Lead(O):} {Fase Lead(O):}
::msgcat::mcset es {Phase angle [in degrees](P):} {Ángulo de la fase [ en degrees](P):}
::msgcat::mcset es Point-Constraints Punto-Constreñimientos
::msgcat::mcset es Point-Disconnect Punto-Desconecte
::msgcat::mcset es Point-Enforced-Displacement {Punto-Hacer cumplir-Dislocación}
::msgcat::mcset es Point-Force-Load Punto-Fuerza-Carga
::msgcat::mcset es {Power input/volume:} {Energía input/volume:}
::msgcat::mcset es {Pressure Freq Type1} {Presión Freq Type1}
::msgcat::mcset es {Pressure Freq Type2} {Presión Freq Type2}
::msgcat::mcset es {Pressure Time Type1} {Tiempo Type1 De la Presión}
::msgcat::mcset es {Pressure Time Type2} {Tiempo Type2 De la Presión}
::msgcat::mcset es {Radiation Boundary} {Límite De la Radiación}
::msgcat::mcset es {Radiation View Factor:} {Factor De la Opinión De la Radiación:}
::msgcat::mcset es SPCFORCES SPCFORCES
::msgcat::mcset es STRAIN TENSIÓN
::msgcat::mcset es STRESS TENSIÓN
::msgcat::mcset es {Scale Factor(A):} {Escala Factor(A):}
::msgcat::mcset es Slave Esclavo
::msgcat::mcset es {Static Loads} {Cargas Estáticas}
::msgcat::mcset es {Superior Time Limit(T2):} {Tiempo Superior Limit(T2):}
::msgcat::mcset es Surface-Constraints Superficie-Constreñimientos
::msgcat::mcset es Surface-Enforced-Displacement {Superficie-Hacer cumplir-Dislocación}
::msgcat::mcset es Surface-Pressure-Load Superficie-Presión-Carga
::msgcat::mcset es {Symmetric mass matrix:} {Matriz total simétrica:}
::msgcat::mcset es {Table Interpolation Values B[f]:} {La Interpolación De la Tabla Valora B[f ]:}
::msgcat::mcset es {Table Interpolation Values C[f]:} {La Interpolación De la Tabla Valora C[f ]:}
::msgcat::mcset es {Table Interpolation Values D[f]:} {La Interpolación De la Tabla Valora D[f ]:}
::msgcat::mcset es {Table Interpolation Values F[t-T]:} {La Interpolación De la Tabla Valora F[t-T ]:}
::msgcat::mcset es {Table Interpolation Values h[f]:} {La interpolación de la tabla valora el h[f ]:}
::msgcat::mcset es Tables Tablas
::msgcat::mcset es Temperature: Temperatura:
::msgcat::mcset es {Thermal Loads} {Cargas Termales}
::msgcat::mcset es {Time Delay(T):} {Tiempo Delay(T):}
::msgcat::mcset es {Time Dynamic Type1} {Tiempo Type1 Dinámico}
::msgcat::mcset es {Time Dynamic Type2} {Tiempo Type2 Dinámico}
::msgcat::mcset es {To disconnect some degrees in one point.One flag chekced-->degree disconnected} {Desconectar algunos grados en una bandera de point.One chekced -- &gt;degree desconectada}
::msgcat::mcset es {Use this condition to assign the Material Cooordinate system orientation.} {Utilice esta condición para asignar la orientación material del sistema de Cooordinate.}
::msgcat::mcset es {V x:} {V x:}
::msgcat::mcset es {V y:} {V y:}
::msgcat::mcset es {V z:} {V z:}
::msgcat::mcset es VELOCITY VELOCIDAD
::msgcat::mcset es Vector Vector
::msgcat::mcset es {Volumetric Heat} {Calor Volumétrico}
::msgcat::mcset es {Volumetric heat} {Calor volumétrico}
::msgcat::mcset es X-Displacement X-Dislocación
::msgcat::mcset es {X-Enforced Displacement:} {Dislocación X-Hecha cumplir:}
::msgcat::mcset es X-Force X-Fuerza
::msgcat::mcset es X-Pressure X-Presión
::msgcat::mcset es {X-Pressure End Point} {Punto final De la X-Presión}
::msgcat::mcset es {X-Pressure Start Point} {Punto Del Comienzo De la X-Presión}
::msgcat::mcset es X-Rotation X-Rotación
::msgcat::mcset es X1 X1
::msgcat::mcset es X2 X2
::msgcat::mcset es X3 X3
::msgcat::mcset es Y-Displacement Y-Dislocación
::msgcat::mcset es {Y-Enforced Displacement:} {Dislocación Y-Hecha cumplir:}
::msgcat::mcset es Y-Force Y-Fuerza
::msgcat::mcset es Y-Pressure Y-Presión
::msgcat::mcset es {Y-Pressure End Point} {Punto final De la Y-Presión}
::msgcat::mcset es {Y-Pressure Start Point} {Punto Del Comienzo De la Y-Presión}
::msgcat::mcset es Y-Rotation Y-Rotación
::msgcat::mcset es Z-Displacement Z-Dislocación
::msgcat::mcset es {Z-Enforced Displacement:} {Dislocación Z-Hecha cumplir:}
::msgcat::mcset es Z-Force Z-Fuerza
::msgcat::mcset es Z-Pressure Z-Presión
::msgcat::mcset es {Z-Pressure End Point} {Punto final De la Z-Presión}
::msgcat::mcset es {Z-Pressure Start Point} {Punto Del Comienzo De la Z-Presión}
::msgcat::mcset es Z-Rotation Z-Rotación
::msgcat::mcset es {cosine/sine Load} {carga de cosine/sine}
::msgcat::mcset es dummy simulado
::msgcat::mcset es dummy1 dummy1
::msgcat::mcset es dummy2 dummy2
::msgcat::mcset es dummy3 dummy3
::msgcat::mcset es dummy4 dummy4
::msgcat::mcset es dummy5 dummy5
::msgcat::mcset es m1 m1
::msgcat::mcset es m2 m2
::msgcat::mcset es m3 m3
::msgcat::mcset es m4 m4
::msgcat::mcset es m5 m5
::msgcat::mcset es m6 m6
::msgcat::mcset es {moments of inertia measured at the mass c.g. in global system} {los momentos de la inercia midieron en la masa c.g. en sistema global}
::msgcat::mcset es -ANY- {- cualesquiera}
::msgcat::mcset es {2 to 4 Blank=Square} {2 a 4 Blank=Square}
::msgcat::mcset es : :
::msgcat::mcset es A1 A1
::msgcat::mcset es A2 A2
::msgcat::mcset es A3 A3
::msgcat::mcset es {Allowable tensile stress:} {Tensión extensible permisible:}
::msgcat::mcset es {Anisotropic Shell} {Cáscara Anisotropic}
::msgcat::mcset es {Area Cross Section:} {Sección transversal Del Área:}
::msgcat::mcset es {Area cross section:} {Sección transversal del área:}
::msgcat::mcset es Area: Área:
::msgcat::mcset es Axial Axial
::msgcat::mcset es BAR BARRA
::msgcat::mcset es BEAM VIGA
::msgcat::mcset es Bar Barra
::msgcat::mcset es Beam Viga
::msgcat::mcset es CABLE CABLE
::msgcat::mcset es CLOSED CERRADO
::msgcat::mcset es {CLOSED=Both ends are closed
OPEN= Both ends are open} {Los extremos de CLOSED=Both son closed
OPEN = ambos extremos están abiertos}
::msgcat::mcset es Cable Cable
::msgcat::mcset es {Coeff. Torsional Stress:} {Coeficientes.  Tensión Torsional:}
::msgcat::mcset es {Connect to} {Conecte con}
::msgcat::mcset es Cp Cp
::msgcat::mcset es Cs Cs
::msgcat::mcset es DOF Dof
::msgcat::mcset es {DOF SPRING} {RESORTE DEL DOF}
::msgcat::mcset es {DOF Spring} {Resorte del Dof}
::msgcat::mcset es Damping: {El humedecer:}
::msgcat::mcset es E1 E1
::msgcat::mcset es E2 E2
::msgcat::mcset es {Effectiveness Factors} {Factores De la Eficacia}
::msgcat::mcset es {End condition} {Condición de final}
::msgcat::mcset es EndA EndA
::msgcat::mcset es EndB EndB
::msgcat::mcset es F12 F12
::msgcat::mcset es F1: F1:
::msgcat::mcset es F2: F2:
::msgcat::mcset es G11 G11
::msgcat::mcset es G12 G12
::msgcat::mcset es G13 G13
::msgcat::mcset es G1Z G1Z
::msgcat::mcset es G22 G22
::msgcat::mcset es G23 G23
::msgcat::mcset es G2Z G2Z
::msgcat::mcset es G33 G33
::msgcat::mcset es Ge GE
::msgcat::mcset es HEXAHEDRON HEXAHEDRON
::msgcat::mcset es Hexahedron Hexahedron
::msgcat::mcset es Hgen Hgen
::msgcat::mcset es I I
::msgcat::mcset es I12: I12:
::msgcat::mcset es I1: I1:
::msgcat::mcset es I2: I2:
::msgcat::mcset es {Initial conditions} {Condiciones iniciales}
::msgcat::mcset es {Internal pressure:} {Presión interna:}
::msgcat::mcset es Isotropic Isotrópico
::msgcat::mcset es K11 K11
::msgcat::mcset es K12 K12
::msgcat::mcset es K13 K13
::msgcat::mcset es K22 K22
::msgcat::mcset es K23 K23
::msgcat::mcset es K33 K33
::msgcat::mcset es LAMINATE LAMINADO
::msgcat::mcset es Laminate Laminado
::msgcat::mcset es Material Material
::msgcat::mcset es {Moment of Inertia:} {Momento de la inercia:}
::msgcat::mcset es {Moments of Inertia:} {Momentos de la inercia:}
::msgcat::mcset es {Nonstructural mass/area:} {Nonstructural mass/area:}
::msgcat::mcset es {Nonstructural mass/length:} {Nonstructural mass/length:}
::msgcat::mcset es OPEN ABIERTO
::msgcat::mcset es {Orthotropic Shell} {Cáscara De Orthotropic}
::msgcat::mcset es {Outside diameter of pipe:} {Diámetro exterior de la pipa:}
::msgcat::mcset es {Outside diameter of tube:} {Diámetro exterior del tubo:}
::msgcat::mcset es PIPE PIPA
::msgcat::mcset es PLATE PLACA
::msgcat::mcset es PROPERTY CARACTERÍSTICA
::msgcat::mcset es Pipe Pipa
::msgcat::mcset es {Pipe wall thickness:} {Grueso de pared de la pipa:}
::msgcat::mcset es Plate Placa
::msgcat::mcset es Property Característica
::msgcat::mcset es {Property Values:} {Valores De Característica:}
::msgcat::mcset es ROD BARRA
::msgcat::mcset es Rod Barra
::msgcat::mcset es S S
::msgcat::mcset es {SHEAR PANEL} {PANEL DEL ESQUILEO}
::msgcat::mcset es SPRING RESORTE
::msgcat::mcset es Sc Sc
::msgcat::mcset es {Shear Panel} {Panel Del Esquileo}
::msgcat::mcset es {Slack U0:} {U0 flojo:}
::msgcat::mcset es {Solid Circular Rod} {Barra Circular Sólida}
::msgcat::mcset es Spring Resorte
::msgcat::mcset es Ss Ss
::msgcat::mcset es St St
::msgcat::mcset es {Stiffness coefficient:} {Coeficiente de la tiesura:}
::msgcat::mcset es Stiffness: Tiesura:
::msgcat::mcset es {Stress Recovery} {Recuperación De la Tensión}
::msgcat::mcset es Strn Strn
::msgcat::mcset es TABLED1 TABLED1
::msgcat::mcset es TABLED2 TABLED2
::msgcat::mcset es TABLED3 TABLED3
::msgcat::mcset es TABLED4 TABLED4
::msgcat::mcset es TETRAHEDRON TETRAEDRO
::msgcat::mcset es TUBE TUBO
::msgcat::mcset es Table Tabla
::msgcat::mcset es {Table Interpolation Values:} {Valores De la Interpolación De la Tabla:}
::msgcat::mcset es {Table parameter1:} {Tabla parameter1:}
::msgcat::mcset es {Table parameter2:} {Tabla parameter2:}
::msgcat::mcset es {Table parameter3:} {Tabla parameter3:}
::msgcat::mcset es {Table parameter4:} {Tabla parameter4:}
::msgcat::mcset es {Tension T0:} {Tensión T0:}
::msgcat::mcset es Tetrahedron Tetraedro
::msgcat::mcset es {The formula used to compute torsional stress is
 Stress=(T*coeff.Torsional)/J
 where T is the torsional moment
 and J torsional moment} {El fórmula computaba el is
 torsional Stress=(T*coeff.Torsional)/J
 de la tensión donde está el moment
 torsional y el momento T torsional de J}
::msgcat::mcset es {The initial cable slack, U0, is the distance the cable must stretch before it will carry load.
The initial cable tension, T0, is the tensile preload in untis of force that exists in the cable at the start of the analisys.} {La holgura inicial del cable, U0, es la distancia que el cable debe estirar antes de que lleve la tensión inicial del cable de load.
The, T0, es la carga extensible en untis de la fuerza que existe en el cable en el comienzo de los analisys.}
::msgcat::mcset es {Thickness of tube:} {Grueso del tubo:}
::msgcat::mcset es Thickness: Espesor:
::msgcat::mcset es Torsional Torsional
::msgcat::mcset es {Torsional Constant:} {Constante Torsional:}
::msgcat::mcset es Tref Tref
::msgcat::mcset es Tube Tubo
::msgcat::mcset es Type Tipo
::msgcat::mcset es {Type of Interpolation:} {Tipo de interpolación:}
::msgcat::mcset es {VISCOUS DAMPER} {APAGADOR VISCOSO}
::msgcat::mcset es {Value type:} {Tipo del valor:}
::msgcat::mcset es Values: Valores:
::msgcat::mcset es {Viscous Damper} {Apagador Viscoso}
::msgcat::mcset es {Viscous coefficient extension:} {Extensión viscosa del coeficiente:}
::msgcat::mcset es {Viscous coefficient rotation:} {Rotación viscosa del coeficiente:}
::msgcat::mcset es Xc Xc
::msgcat::mcset es Xt Xt
::msgcat::mcset es Y Y
::msgcat::mcset es {Y Neutral Axis Offset:} {Eje Neutral De Y Compensado:}
::msgcat::mcset es {Y Shear Area:} {Área Del Esquileo De Y:}
::msgcat::mcset es Yc Yc
::msgcat::mcset es Yt Yt
::msgcat::mcset es Z Z
::msgcat::mcset es {Z Neutral Axis Offset:} {Eje Neutral De Z Compensado:}
::msgcat::mcset es {Z Shear Area:} {Área Del Esquileo De Z:}
::msgcat::mcset es bend curva
::msgcat::mcset es {cable slack} {holgura del cable}
::msgcat::mcset es {cable tension} {tensión del cable}
::msgcat::mcset es compression compresión
::msgcat::mcset es conductivity conductividad
::msgcat::mcset es damping {el humedecer}
::msgcat::mcset es density densidad
::msgcat::mcset es expansion extensión
::msgcat::mcset es {free conv} {conv libre}
::msgcat::mcset es friction fricción
::msgcat::mcset es harden endurezca
::msgcat::mcset es heatgen heatgen
::msgcat::mcset es initial inicial
::msgcat::mcset es {laminate prop} {apoyo laminado}
::msgcat::mcset es {laminate seq} {seq laminado}
::msgcat::mcset es matid matid
::msgcat::mcset es matlist matlist
::msgcat::mcset es {mo shear} {esquileo del MES}
::msgcat::mcset es nastran nastran
::msgcat::mcset es nomass nomass
::msgcat::mcset es nontype nontype
::msgcat::mcset es nu12 nu12
::msgcat::mcset es plasticity plasticidad
::msgcat::mcset es poisson poisson
::msgcat::mcset es rho rho
::msgcat::mcset es shear esquileo
::msgcat::mcset es {spec heat} {calor de espec.}
::msgcat::mcset es stress tensión
::msgcat::mcset es stress-strain stress-strain
::msgcat::mcset es {temp ref} {referencia de la temperatura}
::msgcat::mcset es tension tensión
::msgcat::mcset es thick densamente
::msgcat::mcset es trans transporte
::msgcat::mcset es {win info} {triunfo Info}
::msgcat::mcset es x x
::msgcat::mcset es {y[x]} {y[x ]}
::msgcat::mcset es {yield func} {producción funcional}
::msgcat::mcset es young joven
::msgcat::mcset es ADAPT ADÁPTESE
::msgcat::mcset es AERO AERO-
::msgcat::mcset es AUTO AUTOMÓVIL
::msgcat::mcset es AUTOSPC AUTOSPC
::msgcat::mcset es Acceleration Aceleración
::msgcat::mcset es {Activate Load Cases} {Active Las Cajas De la Carga}
::msgcat::mcset es {Advanced Data} {Datos Avanzados}
::msgcat::mcset es {Ambient Temperature:} {Temperatura Ambiente:}
::msgcat::mcset es {Analysis Type} {Tipo Del Análisis}
::msgcat::mcset es {Applied Load} {Carga Aplicada}
::msgcat::mcset es {Auxiliary Output Points for stress and force recovery output.} {La salida auxiliar señala para la salida de la recuperación de la tensión y de la fuerza.}
::msgcat::mcset es BISECT BISEQUE
::msgcat::mcset es BODYLOAD BODYLOAD
::msgcat::mcset es BOTH AMBOS
::msgcat::mcset es BUCKLING {EL ABROCHAR}
::msgcat::mcset es Buckling {El abrochar}
::msgcat::mcset es {Case Control} {Control Del Caso}
::msgcat::mcset es Center: Centro:
::msgcat::mcset es {Combined load cases:} {Casos combinados de la carga:}
::msgcat::mcset es {Complex Eigenvalue or Frequency Response:} {Respuesta compleja del valor propio o de frecuencia:}
::msgcat::mcset es {Consider Acceleration} {Considere La Aceleración}
::msgcat::mcset es {Constraint Force} {Fuerza Del Constreñimiento}
::msgcat::mcset es {Constraints load cases} {Casos de la carga de los apremios}
::msgcat::mcset es {Convergence tolerance:} {Tolerancia de la convergencia:}
::msgcat::mcset es Conversion Conversión
::msgcat::mcset es Coupled Juntado
::msgcat::mcset es DET DET
::msgcat::mcset es {DIRECT COMPLEX EIGENVALUES} {VALORES PROPIOS COMPLEJOS DIRECTOS}
::msgcat::mcset es {DIRECT FREQUENCY RESPONSE} {RESPUESTA DE FRECUENCIA DIRECTA}
::msgcat::mcset es {DIRECT TRANSIENT RESPONSE} {RESPUESTA TRANSITORIA DIRECTA}
::msgcat::mcset es {DOF (integer 1-6):} {Dof (número entero 1-6):}
::msgcat::mcset es Damping {El humedecer}
::msgcat::mcset es Default {Por defecto}
::msgcat::mcset es Design Diseño
::msgcat::mcset es {Design REAL eigenvalue} {Valor propio VERDADERO del diseño}
::msgcat::mcset es {Design buckling modes} {Modos el abrochar del diseño}
::msgcat::mcset es {Desired number:} {Número deseado:}
::msgcat::mcset es Diagnostics: Diagnóstico:
::msgcat::mcset es Direct Directo
::msgcat::mcset es {Disp. tolerance:} {Tolerancia del Disp.:}
::msgcat::mcset es Displacement Dislocación
::msgcat::mcset es {Displacement Criteria} {Criterios De la Dislocación}
::msgcat::mcset es {Domain of Solution:} {Dominio de la solución:}
::msgcat::mcset es Dynamic Dinámico
::msgcat::mcset es {Dynamic Design} {Diseño Dinámico}
::msgcat::mcset es Dynamics Dinámica
::msgcat::mcset es ECHO: ECO:
::msgcat::mcset es {Eigenvalue range of interest} {Gama del valor propio del interés}
::msgcat::mcset es Eigenvalues {Valores propios}
::msgcat::mcset es Eigenvectors {Vectores propios}
::msgcat::mcset es {Element Corner Output} {Salida De la esquina Del Elemento}
::msgcat::mcset es {Element Force} {Fuerza Del Elemento}
::msgcat::mcset es {Element Strain} {Tensión Del Elemento}
::msgcat::mcset es {Element Stress} {Tensión Del Elemento}
::msgcat::mcset es {Equivalent Viscous} {Viscoso Equivalente}
::msgcat::mcset es {Equivalent Viscous Damping} {El Humedecer Viscoso Equivalente}
::msgcat::mcset es {Estimate number:} {Número de la estimación:}
::msgcat::mcset es {Executive Control} {Control Ejecutivo}
::msgcat::mcset es FEER FEER
::msgcat::mcset es FEER-Q Feer-q
::msgcat::mcset es FEER-X Feer-x
::msgcat::mcset es {Final eigenvalue:} {Valor propio final:}
::msgcat::mcset es {First frequency (Hz):} {Primera frecuencia (hertzio):}
::msgcat::mcset es Flux Flujo
::msgcat::mcset es {Format File:} {Archivo Del Formato:}
::msgcat::mcset es Frequency Frecuencia
::msgcat::mcset es {Frequency Range of} {Gama de frecuencia de}
::msgcat::mcset es {Frequency for Element Damping(W4-Hz):} {Frecuencia para el elemento Damping(W4-Hz):}
::msgcat::mcset es {Frequency for System Damping(W3-Hz):} {Frecuencia para el sistema Damping(W3-Hz):}
::msgcat::mcset es {Frequency increment:} {Incremento de la frecuencia:}
::msgcat::mcset es From(Hz): From(Hz):
::msgcat::mcset es GIMBAL CARDÁN
::msgcat::mcset es GIV GIV
::msgcat::mcset es GPFORCE GPFORCE
::msgcat::mcset es GRDPNT GRDPNT
::msgcat::mcset es Geometry Geometría
::msgcat::mcset es HEAT CALOR
::msgcat::mcset es {Highest Freq(Hz):} {El Freq(Hz) Más alto:}
::msgcat::mcset es ID: Identificación:
::msgcat::mcset es IMAG IMAG
::msgcat::mcset es INRELF INRELF
::msgcat::mcset es INV INV
::msgcat::mcset es IRES IRAS
::msgcat::mcset es ITER ITER
::msgcat::mcset es {Initial eigenvalue:} {Valor propio inicial:}
::msgcat::mcset es {Initial frequency:} {Frecuencia inicial:}
::msgcat::mcset es {Input Data} {Datos De Entrada}
::msgcat::mcset es Interest Interés
::msgcat::mcset es {Interval name} {Nombre del intervalo}
::msgcat::mcset es {Iter stiffness update:} {Actualización de la tiesura de Iter:}
::msgcat::mcset es K6ROT K6ROT
::msgcat::mcset es LANGLE LANGLE
::msgcat::mcset es LGDISP LGDISP
::msgcat::mcset es Label: Etiqueta:
::msgcat::mcset es Large Grande
::msgcat::mcset es {Last frequency (Hz):} {Frecuencia pasada (hertzio):}
::msgcat::mcset es {Lines per printed page:} {Líneas por la página impresa:}
::msgcat::mcset es {Load Criteria} {Criterios De la Carga}
::msgcat::mcset es {Load tolerance:} {Tolerancia de la carga:}
::msgcat::mcset es {Lowest Freq(Hz):} {El Freq(Hz) Más bajo:}
::msgcat::mcset es Lumped Lumped
::msgcat::mcset es MASS MASA
::msgcat::mcset es MAX Máximo
::msgcat::mcset es MAXRATIO: MAXRATIO:
::msgcat::mcset es MGIV MGIV
::msgcat::mcset es MI/NASTRAN MI/NASTRAN
::msgcat::mcset es MODACC MODACC
::msgcat::mcset es {MODAL FREQUENCY RESPONSE} {RESPUESTA DE FRECUENCIA MODAL}
::msgcat::mcset es {MODAL TRANSIENT RESPONSE} {RESPUESTA TRANSITORIA MODAL}
::msgcat::mcset es MODES MODOS
::msgcat::mcset es MPC MPC
::msgcat::mcset es MPCFORCE MPCFORCE
::msgcat::mcset es MSC/NASTRAN MSC/NASTRAN
::msgcat::mcset es MULTBC MULTBC
::msgcat::mcset es {Mass formulation:} {Formulación total:}
::msgcat::mcset es {Mass orthogonality test} {Prueba total del orthogonality}
::msgcat::mcset es {Max iter. divergence:} {Divergencia máxima de iter.:}
::msgcat::mcset es {Max. iter. load increment:} {Incremento máximo de la carga de iter.:}
::msgcat::mcset es {Max. iter. time increment:} {Incremento máximo del tiempo de iter.:}
::msgcat::mcset es {Maximum iterations:} {Iteraciones máximas:}
::msgcat::mcset es {Maximum number of output lines:} {Número máximo de las líneas de salida:}
::msgcat::mcset es {Method of eigenvalue extraction:} {Método de extracción del valor propio:}
::msgcat::mcset es Modal Modal
::msgcat::mcset es {Model Initial Temperature:} {Temperatura Inicial Modelo:}
::msgcat::mcset es Modes Modos
::msgcat::mcset es {Modes Analysis} {Análisis De los Modos}
::msgcat::mcset es {Modul Acceleration:} {Aceleración De Modul:}
::msgcat::mcset es {NASTRAN Type:} {Tipo de NASTRAN:}
::msgcat::mcset es NE/NASTRAN NE/NASTRAN
::msgcat::mcset es {NL Analysis:} {Análisis de NL:}
::msgcat::mcset es NLINSOLACCEL NLINSOLACCEL
::msgcat::mcset es NO NO
::msgcat::mcset es NONE NINGUNOS
::msgcat::mcset es {NONLINEAR BUCKLING} {EL ABROCHAR NO LINEAL}
::msgcat::mcset es {NONLINEAR STATIC} {PARÁSITOS ATMOSFÉRICOS NO LINEALES}
::msgcat::mcset es {NONLINEAR TRANSIENT} {TRANSEÚNTE NO LINEAL}
::msgcat::mcset es NOPRINT NOPRINT
::msgcat::mcset es NodeID: NodeID:
::msgcat::mcset es NonLinear {No lineal}
::msgcat::mcset es {NonLinear Solution} {Solución No lineal}
::msgcat::mcset es Nonlinear {No lineal}
::msgcat::mcset es {Normalization method:} {Método de la normalización:}
::msgcat::mcset es {Num. increments:} {Incrementos numéricos:}
::msgcat::mcset es {Number of Modes:} {Número de modos:}
::msgcat::mcset es {Number of frequency increments:} {Número de los incrementos de la frecuencia:}
::msgcat::mcset es {Number of roots desired:} {El número de raíces deseó:}
::msgcat::mcset es {Number of time steps:} {Número de los pasos del tiempo:}
::msgcat::mcset es OFF DE
::msgcat::mcset es Output Salida
::msgcat::mcset es {Output Data} {Datos De la Salida}
::msgcat::mcset es {Output Device:} {Dispositivo De Salida:}
::msgcat::mcset es {Output Number of frequency increments:} {Número de la salida de los incrementos de la frecuencia:}
::msgcat::mcset es {Overall Structural Damping Coeff(G):} {Coeff(G) Que humedece Estructural Total:}
::msgcat::mcset es PELMCHK PELMCHK
::msgcat::mcset es PHASE FASE
::msgcat::mcset es PLOT DIAGRAMA
::msgcat::mcset es POINT Punto
::msgcat::mcset es {PRESTRESS MODES} {PRETENSE LOS MODOS}
::msgcat::mcset es {PRESTRESS STATIC} {PRETENSE LOS PARÁSITOS ATMOSFÉRICOS}
::msgcat::mcset es PRGPST PRGPST
::msgcat::mcset es PRINT IMPRESIÓN
::msgcat::mcset es PRTGPST PRTGPST
::msgcat::mcset es PUNCH SACADOR
::msgcat::mcset es Parameters Parámetros
::msgcat::mcset es REAL VERDADERO
::msgcat::mcset es ROTATION ROTACIÓN
::msgcat::mcset es {Response Based on} {Respuesta basada encendido}
::msgcat::mcset es {Rigid Format approach:} {Acercamiento rígido del formato:}
::msgcat::mcset es SEMI SEMI
::msgcat::mcset es SINGOPT SINGOPT
::msgcat::mcset es SORT CLASE
::msgcat::mcset es SPC {Proceso estadístico}
::msgcat::mcset es STATIC ESTÁTICO
::msgcat::mcset es {STEADY STATE HEAT TRANSFER} {TRASPASO TÉRMICO DEL ESTADO CONSTANTE}
::msgcat::mcset es STIFF TIESO
::msgcat::mcset es {Scale Factor Abs. Temperature:} {Factor de posicionamiento Abs. Temperature:}
::msgcat::mcset es {Select Range of frequencies for Output} {Seleccione la gama de las frecuencias para la salida}
::msgcat::mcset es {Skip factor for output:} {Factor del salto para la salida:}
::msgcat::mcset es {Skip factor time adjust.:} {El tiempo del factor del salto ajusta:}
::msgcat::mcset es Small Pequeño
::msgcat::mcset es Solution Solución
::msgcat::mcset es {Solution Method:} {Método De la Solución:}
::msgcat::mcset es Static Estático
::msgcat::mcset es Stefan-Boltzmann: Stefan-Stefan-Boltzmann:
::msgcat::mcset es Step Paso
::msgcat::mcset es {Stiffness method} {Método de la tiesura}
::msgcat::mcset es {Stiffness method dyn} {Método dyn de la tiesura}
::msgcat::mcset es {Strain Energy} {Energía De Tensión}
::msgcat::mcset es {Sturm sequence} {Secuencia de Sturm}
::msgcat::mcset es Subtitle: Subtítulo:
::msgcat::mcset es TIME(min): TIME(min):
::msgcat::mcset es TSTEP TSTEP
::msgcat::mcset es {Time increment:} {Incremento del tiempo:}
::msgcat::mcset es Title: Título:
::msgcat::mcset es {Tolerance for Mass orthogonality test:} {Tolerancia para la prueba total del orthogonality:}
::msgcat::mcset es Tolerance: Tolerancia:
::msgcat::mcset es Transient Transitorio
::msgcat::mcset es {Transient Time} {Tiempo Transitorio}
::msgcat::mcset es UDET UDET
::msgcat::mcset es UINV UINV
::msgcat::mcset es UNSORT UNSORT
::msgcat::mcset es Velocity Velocidad
::msgcat::mcset es WTMASS: WTMASS:
::msgcat::mcset es {Work Criteria} {Criterios Del Trabajo}
::msgcat::mcset es {Work tolerance:} {Tolerancia del trabajo:}
::msgcat::mcset es {X-Acceleration Vector:} {Vector De la X-Aceleración:}
::msgcat::mcset es {Y-Acceleration Vector:} {Vector De la Y-Aceleración:}
::msgcat::mcset es YES SÍ
::msgcat::mcset es {Z-Acceleration Vector:} {Vector De la Z-Aceleración:}
::msgcat::mcset es combined combinado
::msgcat::mcset es criteria criterios
::msgcat::mcset es extraction extracción
::msgcat::mcset es independent independiente
::msgcat::mcset es {interval data} {datos del intervalo}
::msgcat::mcset es isstrength isstrength
::msgcat::mcset es loads cargas
::msgcat::mcset es name nombre
::msgcat::mcset es prestress pretense
