#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es About {Acerca de}
::msgcat::mcset es {domain body of surface} {dominio cuerpo de superficie}
::msgcat::mcset es {domain body of volume} {dominio cuerpo de volúmen}
::msgcat::mcset es {domain edge of surface} {dominio arista de superficie}
::msgcat::mcset es {domain face of volume} {dominio cara de volúmen}
::msgcat::mcset es {domains 2d} {dominios 2d}
::msgcat::mcset es {domains 3d} {dominios 3d}
::msgcat::mcset es id identificador
::msgcat::mcset es {integer number to identify a domain} {número entero que identifica un dominio}
::msgcat::mcset es {mesh function body of volume} {función malla cuerpo de volúmen}
::msgcat::mcset es {mesh function face of volume} {función malla cara de volúmen}
::msgcat::mcset es {mesh function value} {valor función malla}
::msgcat::mcset es {mesh functions} {funciones malla}
::msgcat::mcset es value valor
::msgcat::mcset es Dolfin Dolfin
::msgcat::mcset es Epetra Epetra
::msgcat::mcset es MTL4 MTL4
::msgcat::mcset es PETSc PETSc
::msgcat::mcset es {absolute tolerance} {tolerancia absoluta}
::msgcat::mcset es {allow extrapolation} {permitir extrapolación}
::msgcat::mcset es {cache dir} {directorio cache }
::msgcat::mcset es {convert exceptions to warnings} {convertir excepciones en avisos}
::msgcat::mcset es {cpp optimize} {optimizar c++}
::msgcat::mcset es {cpp optimize flags} {parámetros de optimización c++}
::msgcat::mcset es {divergence limit} {límite de divergencia}
::msgcat::mcset es epsilon epsilon
::msgcat::mcset es {error control} {control de error}
::msgcat::mcset es {error on nonconvergence} {error si no converge}
::msgcat::mcset es {exact interpolation} {interpolación exacta}
::msgcat::mcset es false falso
::msgcat::mcset es {form compiler} {form compilador}
::msgcat::mcset es {form postfix} {form sufijo}
::msgcat::mcset es format formato
::msgcat::mcset es {gmres restart} {gmres reiniciar}
::msgcat::mcset es {graph coloring library} {biblioteca de coloreado de grafos}
::msgcat::mcset es {krylov solver} {solucionador krylov}
::msgcat::mcset es {linear algebra backend} {paquete algegra lineal}
::msgcat::mcset es {log level} {nivel log}
::msgcat::mcset es {log prefix} {prefijo log}
::msgcat::mcset es {lu solver} {solucionador lu}
::msgcat::mcset es {maximum iterations} {máximo iteraciones}
::msgcat::mcset es {mesh partitioner} {particionador malla}
::msgcat::mcset es {monitor convergence} {monitorizar convergencia}
::msgcat::mcset es name nombre
::msgcat::mcset es {nonzero initial guess} {previsión incial no nulos}
::msgcat::mcset es {num threads} {número hilos}
::msgcat::mcset es {optimize dolfin} {optimizar dolfin}
::msgcat::mcset es {optimize form} {optimizar form}
::msgcat::mcset es {optimize form compiler} {optimizar compilador form}
::msgcat::mcset es {optimize use dofmap cache} {optimizar uso dofmap cache}
::msgcat::mcset es {optimize use tensor cache} {optimizar uso tensor cache}
::msgcat::mcset es {output dir} {directorio salida}
::msgcat::mcset es {plot filename prefix} {prefijo fichero plot}
::msgcat::mcset es precision precisión
::msgcat::mcset es {preconditioner ilu fill level} {preconcionador ilu nivel llenado}
::msgcat::mcset es {preconditioner report} {informe precondicionador}
::msgcat::mcset es {preconditioner reuse} {reusar precondicionador}
::msgcat::mcset es {preconditioner same nonzero pattern} {precondicionador mismo patrón no nulos}
::msgcat::mcset es {preconditioner schwarz overlap} {precondicionador schwarz solapamiento}
::msgcat::mcset es {preconditioner shift nonzero} {precondicionador desplazar no nulos}
::msgcat::mcset es {quadrature degree} {nivel cuadratura}
::msgcat::mcset es {quadrature rule} {regla cuadratura}
::msgcat::mcset es {refinement algorithm} {algorimo refinamiento}
::msgcat::mcset es {relative tolerance} {tolerancia relativa}
::msgcat::mcset es report informe
::msgcat::mcset es representation representación
::msgcat::mcset es {reuse factorization} {reusar factorización}
::msgcat::mcset es {same nonzero pattern} {mismo patrón no nulos}
::msgcat::mcset es solver solucionador
::msgcat::mcset es solvers solucionadores
::msgcat::mcset es split dividir
::msgcat::mcset es {std out all processes} {salida estandar todos procesos}
::msgcat::mcset es {timer prefix} {prefijo timer}
::msgcat::mcset es {to allow extrapolate functions outside the computational domain} {para permitir extrapolar funciones fuera del dominio computacional}
::msgcat::mcset es true verdadero
::msgcat::mcset es uBLAS uBLAS
::msgcat::mcset es {Help on} {Ayuda de}
