#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es AC3D20 AC3D20
::msgcat::mcset es AC3D8 AC3D8
::msgcat::mcset es B31 B31
::msgcat::mcset es B31H B31H
::msgcat::mcset es B32 B32
::msgcat::mcset es B32R B32R
::msgcat::mcset es B33 B33
::msgcat::mcset es B33H B33H
::msgcat::mcset es B34 B34
::msgcat::mcset es {Beam formulation:} {Formulación vigas:}
::msgcat::mcset es C3D10 C3D10
::msgcat::mcset es C3D10E C3D10E
::msgcat::mcset es C3D10H C3D10H
::msgcat::mcset es C3D10MH C3D10MH
::msgcat::mcset es C3D15 C3D15
::msgcat::mcset es C3D15E C3D15E
::msgcat::mcset es C3D15H C3D15H
::msgcat::mcset es C3D20 C3D20
::msgcat::mcset es C3D20E C3D20E
::msgcat::mcset es C3D20H C3D20H
::msgcat::mcset es C3D20HT C3D20HT
::msgcat::mcset es C3D20R C3D20R
::msgcat::mcset es C3D20RH C3D20RH
::msgcat::mcset es C3D20RHT C3D20RHT
::msgcat::mcset es C3D20RT C3D20RT
::msgcat::mcset es C3D20T C3D20T
::msgcat::mcset es C3D4 C3D4
::msgcat::mcset es C3D4E C3D4E
::msgcat::mcset es C3D4H C3D4H
::msgcat::mcset es C3D6 C3D6
::msgcat::mcset es C3D6E C3D6E
::msgcat::mcset es C3D6H C3D6H
::msgcat::mcset es C3D8 C3D8
::msgcat::mcset es C3D8E C3D8E
::msgcat::mcset es C3D8H C3D8H
::msgcat::mcset es C3D8HT C3D8HT
::msgcat::mcset es C3D8I C3D8I
::msgcat::mcset es C3D8IH C3D8IH
::msgcat::mcset es C3D8R C3D8R
::msgcat::mcset es C3D8RH C3D8RH
::msgcat::mcset es C3D8T C3D8T
::msgcat::mcset es CD310M CD310M
::msgcat::mcset es CDD20RE CDD20RE
::msgcat::mcset es DC3D10 DC3D10
::msgcat::mcset es DC3D10E DC3D10E
::msgcat::mcset es DC3D15 DC3D15
::msgcat::mcset es DC3D15E DC3D15E
::msgcat::mcset es DC3D20 DC3D20
::msgcat::mcset es DC3D20E DC3D20E
::msgcat::mcset es DC3D4 DC3D4
::msgcat::mcset es DC3D4E DC3D4E
::msgcat::mcset es DC3D6 DC3D6
::msgcat::mcset es DC3D6E DC3D6E
::msgcat::mcset es DC3D8 DC3D8
::msgcat::mcset es DC3D8E DC3D8E
::msgcat::mcset es DCC3D8D DCC3D8D
::msgcat::mcset es DK3D8N DK3D8N
::msgcat::mcset es DS3 DS3
::msgcat::mcset es DS4 DS4
::msgcat::mcset es DS6 DS6
::msgcat::mcset es DS8 DS8
::msgcat::mcset es {Element formulation} {Formulación elemento}
::msgcat::mcset es {Element type:} {Tipo elemento:}
::msgcat::mcset es Elset {Set elemento}
::msgcat::mcset es GK3D12M GK3D12M
::msgcat::mcset es GK3D18 GK3D18
::msgcat::mcset es GK3D18N GK3D18N
::msgcat::mcset es GK3D2 GK3D2
::msgcat::mcset es GK3D2N GK3D2N
::msgcat::mcset es GK3D6 GK3D6
::msgcat::mcset es GK3D6N GK3D6N
::msgcat::mcset es GK3D8 GK3D8
::msgcat::mcset es Hexahedra Hexaedro
::msgcat::mcset es {Hexahedra formulation:} {Formulación hexaedro:}
::msgcat::mcset es M3D3 M3D3
::msgcat::mcset es M3D4 M3D4
::msgcat::mcset es M3D4R M3D4R
::msgcat::mcset es M3D6 M3D6
::msgcat::mcset es M3D8 M3D8
::msgcat::mcset es M3D8R M3D8R
::msgcat::mcset es Name Nombre
::msgcat::mcset es Nset {Set nodos}
::msgcat::mcset es PIPE31 PIPE31
::msgcat::mcset es PIPE31H PIPE31H
::msgcat::mcset es Prism Prisma
::msgcat::mcset es {Prism formulation:} {Formulación prisma:}
::msgcat::mcset es Quadrilateral Cuadrilátero
::msgcat::mcset es {Quadrilateral formulation:} {Formulación cuadrilátero:}
::msgcat::mcset es R3D3 R3D3
::msgcat::mcset es R3D4 R3D4
::msgcat::mcset es S3 S3
::msgcat::mcset es S3R S3R
::msgcat::mcset es S4 S4
::msgcat::mcset es S4R S4R
::msgcat::mcset es S4R5 S4R5
::msgcat::mcset es S6 S6
::msgcat::mcset es S8 S8
::msgcat::mcset es S8R S8R
::msgcat::mcset es S8R5 S8R5
::msgcat::mcset es S8RT S8RT
::msgcat::mcset es STRI3 STRI3
::msgcat::mcset es STRI35 STRI35
::msgcat::mcset es STRI65 STRI65
::msgcat::mcset es Tetrahedra Tetraedro
::msgcat::mcset es {Tetrahedra formulation:} {Formulación tetraedro:}
::msgcat::mcset es Triangle Triángulo
::msgcat::mcset es {Triangle formulation:} {Formulación triángulo:}
::msgcat::mcset es {AISI 4340 Steel} {AISI 4340 Acero}
::msgcat::mcset es Density Densidad
::msgcat::mcset es {Poisson Ratio} {Módulo poisson}
::msgcat::mcset es {Young Modulus} {Módulo young}
::msgcat::mcset es {Enter the name for the set} {Entrar el nombre del set}
::msgcat::mcset es {Name is not valid} {El nombre no es válido}
::msgcat::mcset es {Name is too long} {El nombre es demasiado largo}
::msgcat::mcset es Sets Sets
::msgcat::mcset es {Surface set} {Set superficies}
::msgcat::mcset es SurfaceNodeset {Set nodos superficie}
::msgcat::mcset es {ABAQUS interface help} {Ayuda interface Abaqus}
::msgcat::mcset es {About Abaqus interface} {Acerca de la interface Abaqus}
::msgcat::mcset es {Define sets} {Definir sets}
::msgcat::mcset es {Output file} {Fichero salida}
::msgcat::mcset es {ABAQUS bar} {Barra ABAQUS}
::msgcat::mcset es {Choose ABAQUS libraries directory} {Seleccionar directorio de librerias ABAQUS}
::msgcat::mcset es {The selected directory does not seem to contain ABAQUS libraries. Proceed?} {El directorio seleccionado no parece contener librerias de ABAQUS. ¿Continuar?}
::msgcat::mcset es {ABAQUS results file} {Fichero resultados ABAQUS}
::msgcat::mcset es B21 B21
::msgcat::mcset es B21H B21H
::msgcat::mcset es B22 B22
::msgcat::mcset es B23 B23
::msgcat::mcset es B23H B23H
::msgcat::mcset es C3D27 C3D27
::msgcat::mcset es {Entered element:} {Elemento entrado:}
::msgcat::mcset es PIPE21 PIPE21
::msgcat::mcset es PIPE21H PIPE21H
::msgcat::mcset es S9 S9
::msgcat::mcset es SAX1 SAX1
::msgcat::mcset es {User defined} {Definido por el usuario}
::msgcat::mcset es {This is the limited version of GiD-Abaqus interface. Please go to Help->Register Problem type and enter the password} {Esta es una versión limitiada de la interface GiD-Abaqus. Por favor vaya a Ayuda->Registrar tipo de problema y entre su clave}
::msgcat::mcset es {This is the evaluation version of GiD-Abaqus interface. Please enter your password or go to Help->Get Problem Type password} {Esta es una versión limitiada de la interface GiD-Abaqus. Por favor vaya a Ayuda->Registrar tipo de problema y entre su clave}
::msgcat::mcset es {Error writing abaqus.ini file} {Error en la escritura de abaqus.ini}
::msgcat::mcset es {Evaluation version works with 2000 nodes max. Please enter your password or go to Help->Get Problem type password} {La versión de evaluación funciona con un máximo de 2000 nodos. Por favor entre su clave o vaya a Ayuda->Conseguir clave Tipo de Problema para conseguir una nueva}
::msgcat::mcset es {Get Problem type password} {Conseguir clave Tipo de Problema}
::msgcat::mcset es {Define sets and element formulation} {Definir sets y formulación de los elementos}
::msgcat::mcset es {Define and apply elastic materials} {Definir y aplicar materiales elásticos}
::msgcat::mcset es {Define local axes systems} {Definir sistemas de ejes locales}
::msgcat::mcset es {Output .inp file for ABAQUS simulations} {Escribir fichero .inp para simulaciones con ABAQUS}
::msgcat::mcset es {Some $elemtype mesh elements are related with $element_type elements formulation} {Algunos elementos de malla $elemtype estan relacionados con formulaciones de elementos $element:type}
::msgcat::mcset es {Error, not supported element type} {Error, tipo de elemento no soportado}
::msgcat::mcset es {Error in condition 'Surface set'. It cannot be applied to the element $num, bad element type} {Error en la conidión "Surface set". No puede ser aplicada sobre el elemento $num, ya que se trata de un tipo de elemento incorrecto}
::msgcat::mcset es {error loading library} {Error cargando la librería}
::msgcat::mcset es C3D10M C3D10M
::msgcat::mcset es {This problemtype requires GiD %s or later} {Este tipo de problema requiere GiD %s o posterior}
