#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es X-Force Fuerza-X
::msgcat::mcset es X-Moment Momento-X
::msgcat::mcset es X-Rotation Rotación-X
::msgcat::mcset es X-Translation Traslación-X
::msgcat::mcset es Y-Force Fuerza-Y
::msgcat::mcset es Y-Moment Momento-Y
::msgcat::mcset es Y-Rotation Rotación-Y
::msgcat::mcset es Y-Translation Traslación-Y
::msgcat::mcset es Z-Force Fuerza-Z
::msgcat::mcset es Z-Moment Momento-Z
::msgcat::mcset es Z-Rotation Rotación-Z
::msgcat::mcset es Z-Translation Traslación-Z
::msgcat::mcset es Concrete Hormigón
::msgcat::mcset es E E
::msgcat::mcset es Iron Hierro
::msgcat::mcset es Masonry {Obra fábrica}
::msgcat::mcset es Mass Masa
::msgcat::mcset es {Poisson's ratio} {Coeficiente Poisson}
::msgcat::mcset es Steel Acero
::msgcat::mcset es Thickness Espesor
::msgcat::mcset es Weight Peso
::msgcat::mcset es Wood Madera
::msgcat::mcset es Active Activado
::msgcat::mcset es Deactive Desctivado
::msgcat::mcset es {Factor scale Model} {Factor escala modelo}
::msgcat::mcset es {SAP2000 Version} {Versión SAP2000}
::msgcat::mcset es {Scale color number} {Número colores escala}
::msgcat::mcset es {Self weight} {Peso propio}
::msgcat::mcset es Shell Lámina
::msgcat::mcset es Units Unidades
::msgcat::mcset es {SAP2000 file} {Fichero SAP2000}
::msgcat::mcset es {Read SAP2000} {Leer SAP2000}
::msgcat::mcset es {Before Reading SAP2000, a project title is needed. Save project to get it} {Antes de leer el fichero SAP2000 es necesario un título de proyecto. Salve el proyecto}
::msgcat::mcset es {SAP2000 file read. It is possible to postprocess now} {Fichero SAP2000 leido. Ahora es posible postprocesarlo}
::msgcat::mcset es {Coord centre base model} {Coord. centro base modelo}
::msgcat::mcset es {Lower limit} {Límite inferior}
::msgcat::mcset es {Upper limit} {Límite superior}
::msgcat::mcset es Load Carga
::msgcat::mcset es Momentum Momento
::msgcat::mcset es No No
::msgcat::mcset es Restraints Restricciones
::msgcat::mcset es Yes Si
::msgcat::mcset es Behavior Comportamiento
::msgcat::mcset es {Degree of freedom DX} {Grado de libertad DX}
::msgcat::mcset es {Degree of freedom DY} {Grado de libertad DY}
::msgcat::mcset es {Degree of freedom DZ} {Grado de libertad DZ}
::msgcat::mcset es {Degree of freedom ROTX} {Grado de libertad ROTX}
::msgcat::mcset es {Degree of freedom ROTY} {Grado de libertad ROTY}
::msgcat::mcset es {Degree of freedom ROTZ} {Grado de libertad ROTZ}
::msgcat::mcset es Membrane Membrana
::msgcat::mcset es Plate Placa
::msgcat::mcset es Solid Sólido
::msgcat::mcset es {enable or disable the self-weigh load} {activa o desactiva la carga de peso propio}
::msgcat::mcset es {format version or the .s2k file written as input for SAP2000 (version formats could have small differences)} {versión de formato}
::msgcat::mcset es {set the kind of structural model and implicilty its degrees of freedom} {establece el tipo de modelo estructural}
::msgcat::mcset es {Help on SAP2000} {Ayuda de SAP2000}
::msgcat::mcset es {Import SAP2000 mesh} {Importar malla SAP2000}
::msgcat::mcset es {Convert SAP2000 results} {Convertir resultado SAP2000}
::msgcat::mcset es {Export VRML file} {Exportar fichero VRML}
::msgcat::mcset es About {Acerca de}
::msgcat::mcset es {Interface developed by: %s
 updated by %s} {Interfaz desarrollada por: %s
 actualizada por %s}
::msgcat::mcset es {SAP2000 file read} {Leer fichero SAP2000}
::msgcat::mcset es {File read} {Fichero leido}
::msgcat::mcset es {VRML results export} {Exportar fichero VRML}
::msgcat::mcset es {Result to export} {Resultado a exportar}
::msgcat::mcset es {Base Model} {Base modelo}
::msgcat::mcset es Export Exportar
::msgcat::mcset es Close Cerrar
::msgcat::mcset es {VRML file %s created.} {Fichero VRML '%s' creado}
::msgcat::mcset es {can't open file %s} {no se puede abrir el fichero '%s'}
::msgcat::mcset es {format version of the .s2k file written as input for SAP2000 (version formats could have small differences)} {version del formato del fichero .s2k de entrada para SAP2000 (puede haber ligeras diferencias entre versiones)}
::msgcat::mcset es Loads Cargas
